import type { Metadata } from "next";
import Script from "next/script";
import {
  Geist,
  Geist_Mono,
  Roboto,
  Inter,
  Pattaya,
  Anton,
} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { CartContextProvider } from "@/app/context/CartContext";
import { SessionContextProvider } from "@/app/context/SessionContext";
import { Toaster } from "sonner";

export const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

export const geistMono = Geist_Mono({
  variable: "--font-geist_mono",
  subsets: ["latin"],
});

export const anton = Anton({
  subsets: ["latin"],
  weight: "400",
});

export const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const pattaya = Pattaya({
  weight: ["400"],
  variable: "--font-pattaya",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Burgerli - Hamburguesas Caseras",
  description: "Generated by create next app",
  icons: "./logo.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <Script
          src="https://t.contentsquare.net/uxa/78c58af8b6052.js"
          strategy="afterInteractive"
        />
      </head>
      <SessionContextProvider>
        <CartContextProvider>
          <body className={`${roboto.className} bg-[#FCEDCC] antialiased`}>
            <Toaster position="top-center" richColors />
            <Header />
            {children}
            <Footer />
          </body>
        </CartContextProvider>
      </SessionContextProvider>
    </html>
  );
}
