import type { Metadata } from "next";
import Script from "next/script";
import {
  Geist,
  Geist_Mono,
  Roboto,
  Inter,
  Pattaya,
  Anton,
} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { CartContextProvider } from "@/app/context/CartContext";
import { SessionContextProvider } from "@/app/context/SessionContext";
import { Toaster } from "sonner";

export const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

export const geistMono = Geist_Mono({
  variable: "--font-geist_mono",
  subsets: ["latin"],
});

export const anton = Anton({
  subsets: ["latin"],
  weight: "400",
});

export const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const pattaya = Pattaya({
  weight: ["400"],
  variable: "--font-pattaya",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Burgerli - Hamburguesas Caseras",
  description: "Generated by create next app",
  icons: "./logo.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <Script id="gtm-script" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-MXTKF82B');
          `}
        </Script>
        <Script
          src="https://t.contentsquare.net/uxa/78c58af8b6052.js"
          strategy="afterInteractive"
        />
      </head>
      <SessionContextProvider>
        <CartContextProvider>
          <body className={`${roboto.className} bg-[#FCEDCC] antialiased`}>
            <noscript>
              <iframe
                src="https://www.googletagmanager.com/ns.html?id=GTM-MXTKF82B"
                height="0"
                width="0"
                style={{ display: "none", visibility: "hidden" }}
              />
            </noscript>
            <Toaster position="top-center" richColors />
            <Header />
            {children}
            <Footer />
          </body>
        </CartContextProvider>
      </SessionContextProvider>
    </html>
  );
}
